import { useState, createContext, useContext } from 'react';

export type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | null>(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.overview': 'Team Overview',
    'nav.gantt': 'Annual Gantt',
    'nav.projects': 'Projects',
    'nav.timetracking': 'Time Tracking',
    'nav.meetings': 'Meetings',
    'nav.analytics': 'Analytics',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    
    // Header
    'header.title': 'Bureau d\'Études',
    'header.subtitle': 'Project Management & Gantt',
    
    // Auth
    'auth.signIn': 'Sign in to your account',
    'auth.signin': 'Sign in to your account',
    'auth.email': 'Email address',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.signingIn': 'Signing in...',
    
    // Projects
    'projects.title': 'Projects',
    'projects.subtitle': 'Manage all Bureau d\'Études projects',
    'projects.new_project': 'New Project',
    'projects.search': 'Search projects...',
    'projects.no_projects': 'No projects yet.',
    'projects.no_search_results': 'No projects found matching your search.',
    
    // Project Form
    'project.edit': 'Edit Project',
    'project.new': 'New Project',
    'project.bc_order': 'Business Central Order Number',
    'project.lookup': 'Lookup',
    'project.order_found': '✓ Order found and data imported',
    'project.name': 'Project Name',
    'project.client': 'Client',
    'project.collection': 'Collection/Modèles',
    'project.composition': 'Composition',
    'project.date_brief': 'Date of Brief',
    'project.status': 'Status',
    'project.commercial': 'Commercial/Chargé d\'affaires',
    'project.atelier': 'Atelier',
    'project.be_team': 'BE Team Member',
    'project.key_dates': 'Key Dates & Deadlines',
    'project.start_be': 'Start in BE',
    'project.wood_foam': 'Wood/Foam Launch',
    'project.delivery': 'Previewed Delivery',
    'project.last_call': 'Last Call',
    'project.hours_previewed': 'Hours Previewed',
    'project.hours_completed': 'Hours Completed',
    'project.view_gantt': 'View Project Gantt',
    'project.cancel': 'Cancel',
    'project.create': 'Create Project',
    'project.update': 'Update Project',
    
    // Gantt
    'gantt.title': 'Annual Gantt Overview',
    'gantt.subtitle': 'Projects sorted by next key date',
    'gantt.project_column_title': 'Project',
    'gantt.export': 'Export',
    'gantt.week': 'Week',
    'gantt.year': 'Year',
    'gantt.quarter': 'Quarter',
    'gantt.month': 'Month',
    'gantt.all_status': 'All Status',
    'gantt.all_categories': 'All Categories',
    'gantt.back_overview': 'Back to Overview',
    'gantt.key_dates': 'Key Dates',
    'gantt.task_phase': 'Task / Phase',
    'gantt.no_tasks': 'No tasks defined for this project yet.',
    'gantt.tasks_appear': 'Tasks will appear here once they are created.',
    'gantt.manage_tasks': 'Manage Tasks',
    'gantt.today': 'Today',

    // Key Dates
    'gantt.wood_foam_launch': 'Wood/Foam Launch',
    'gantt.previewed_delivery': 'Previewed Delivery',
    'gantt.last_call': 'Last Call',
    
    // Task Categories
    'overview.title': 'Team Workload Overview',
    'overview.subtitle': 'BE Team workload and project distribution analysis',
    'overview.be_team_members': 'BE Team Members',
    'overview.active_projects': 'Active Projects',
    'overview.overdue_projects': 'Overdue Projects',
    'overview.avg_utilization': 'Avg. Utilization',
    'overview.capacity': 'Capacity',
    'overview.overdue': 'overdue',
    'overview.total_hours': 'Total Hours',
    'overview.completed': 'Completed',
    'overview.no_active_projects': 'No active projects',
    'overview.available_assignment': 'Available for new assignments',
    'overview.progress': 'Progress',
    'overview.next': 'Next',
    'overview.more_projects': 'more projects',
    
    'task.be_plans_validation': 'BE plans pour validation',
    'task.be_etude_conception': 'BE étude conception',
    'task.commande_mousse': 'Commande mousse',
    'task.be_prepare_fichiers_decoupe': 'BE prépare fichiers découpe bois 2D / dossier atelier',
    'task.reception_mousse': 'Reception mousse',
    'task.decoupe_bois_montage': 'Découpe bois + montage',
    'task.reception_structure_bois': 'Reception structure bois à Chenn',
    'task.gandage_mise_mousse': 'Gandage et Mise en mousse',
    'task.reception_tissu': 'Reception tissu',
    'task.confection': 'Confection (coupe/couture)',
    'task.tapisserie': 'Tapisserie',
    'task.rdv_confort_test_atelier': 'Rdv confort test atelier',
    'task.rdv_confort_structure_bois': 'RDV confort sur structure bois canapé',
    'task.modifs_mousse_post_rdv': 'Modifs mousse post-rdv confort',
    'task.pose_sangles_toile': 'Pose des sangles et/ou toile polypro',
    'task.modifs_bois_post_montage': 'Modifs bois post-montage proto',
    'task.placage_bois': 'Placage bois',
    'task.vernis_placage_bois': 'Vernis placage bois',
    'task.rdv_confort_validation_blanc': 'Rdv confort / validation mise en blanc',
    'task.livraison_ebeniste': 'Livraison EBENISTE',
    'task.controle_qualite': 'Control Qualité',
    'task.depart_palette_moreau': 'Départ palette Moreau',
    'task.autre_a_definir': 'Autre à définir',
    
    // Task Management
    'tasks.manage': 'Manage Project Tasks',
    'tasks.reorder': 'Drag to reorder tasks',
    'tasks.enabled_tasks': 'Enabled Tasks',
    'tasks.available_tasks': 'Available Tasks',
    'tasks.save': 'Save Tasks',
    'tasks.cancel': 'Cancel',
    'tasks.edit_task': 'Edit Task',
    'tasks.task_name': 'Task Name',
    'tasks.start_date': 'Start Date',
    'tasks.end_date': 'End Date',
    'tasks.assignee': 'Assignee',
    'tasks.unassigned': 'Unassigned',
    'tasks.status': 'Status',
    'tasks.progress': 'Progress',
    'tasks.dependencies': 'Dependencies',
    'tasks.dependencies_help': 'Select tasks that must be completed before this task can start',
    'tasks.no_other_tasks': 'No other tasks available',
    
    // Sub Categories
    'subcategory.dev_in_progress': 'Projects in Development',
    'subcategory.prod_with_be_tracking': 'Projects in Production with BE Tracking',
    'subcategory.updates_nomenclature': 'Updates Required / Nomenclature Edition + Series Monitoring',
    'subcategory.waiting_order': 'Projects Waiting for Order',
    'subcategory.completed': 'Completed Projects',
    'subcategory.on_hold': 'Projects On Hold',
    
    // Status
    'status.planning': 'Planning',
    'status.in_progress': 'In Progress',
    'status.at_risk': 'At Risk',
    'status.overdue': 'Overdue',
    'status.completed': 'Completed',
    'status.on_hold': 'On Hold',
    'status.pending': 'Pending',
    'status.blocked': 'Blocked',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.access_denied': 'Access Denied',
    'common.admin_required': 'You need administrator privileges to access user management.',
    
    // Users
    'users.title': 'Team Management',
    'users.subtitle': 'Manage team members, roles, and permissions',
    'users.users': 'users',
    'users.add_user': 'Add User',
    'users.search': 'Search users...',
    'users.all_roles': 'All Roles',
    'users.admin': 'Admin',
    'users.team_member': 'Team Member',
    'users.commercial': 'Commercial',
    'users.atelier': 'Atelier',
    'users.all_status': 'All Status',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.pending': 'Pending',
    'users.user': 'User',
    'users.role': 'Role',
    'users.department': 'Department',
    'users.status': 'Status',
    'users.last_login': 'Last Login',
    'users.actions': 'Actions',
    'users.never': 'Never',
    'users.permissions': 'Permissions',
    
    // Time Tracking
    'timetracking.title': 'Time Tracking',
    'timetracking.subtitle': 'Log your daily hours and track project progress',
    'timetracking.add_entry': 'Add Time Entry',
    'timetracking.today_hours': 'Today\'s Hours',
    'timetracking.today_entries': 'Today\'s Entries',
    'timetracking.active_projects': 'Active Projects',
    'timetracking.project': 'Project',
    'timetracking.select_project': 'Select a project',
    'timetracking.hours': 'Hours',
    'timetracking.date': 'Date',
    'timetracking.task_category': 'Task Category',
    'timetracking.select_category': 'Select task category',
    'timetracking.description': 'Description',
    'timetracking.description_placeholder': 'Describe the work performed...',
    'timetracking.save_entry': 'Save Entry',
    'timetracking.recent_entries': 'Recent Time Entries',
    'timetracking.no_entries': 'No time entries yet',
    'timetracking.add_first_entry': 'Add your first time entry to start tracking',
    'timetracking.enable_notifications': 'Enable Daily Reminders',
    'timetracking.notification_description': 'Get reminded at 5:30 PM each day to log your hours',
    
  // Meetings
  'meetings.title': 'Meetings',
  'meetings.subtitle': 'Manage project meetings and notes',
    'meetings.new_meeting': 'New Meeting',
    'meetings.edit_meeting': 'Edit Meeting',
    'meetings.search': 'Search meetings...',
    'meetings.all_projects': 'All Projects',
    'meetings.no_meetings': 'No meetings yet',
    'meetings.create_first': 'Create your first meeting to get started',
    'meetings.project': 'Project',
    'meetings.select_project': 'Select a project',
    'meetings.date': 'Date',
  'meetings.title_field': 'Meeting Title',
  'meetings.title_placeholder': 'Enter meeting title...',
    'meetings.attendees': 'Attendees',
    'meetings.people': 'people',
    'meetings.photos': 'Photos',
    'meetings.upload_photos': 'Upload Photos',
    'meetings.photo_caption': 'Add caption...',
    'meetings.remove_photo': 'Remove Photo',
    'meetings.notes': 'Meeting Notes',
    'meetings.notes_placeholder': 'Enter meeting notes...',
    'meetings.voice_notes': 'Voice Notes',
    'meetings.start_voice': 'Start Voice-to-Text',
    'meetings.stop_voice': 'Stop Voice-to-Text',
    'meetings.record_audio': 'Record Audio',
    'meetings.recording': 'Recording',
    'meetings.voice_note': 'Voice Note',
    'meetings.no_notes': 'No notes added',
    'meetings.created_by': 'Created by',
    'meetings.view': 'View',
    'meetings.edit': 'Edit',
    'meetings.delete': 'Delete',
    'meetings.create': 'Create Meeting',
    'meetings.update': 'Update Meeting',
    'meetings.confirm_delete': 'Are you sure you want to delete this meeting?',
    
    // Photo Editor
    'photo.edit_annotate': 'Edit & Annotate Photo',
    'photo.drawing_tools': 'Drawing Tools',
    'photo.pen': 'Pen',
    'photo.eraser': 'Eraser',
    'photo.text': 'Text',
    'photo.shapes': 'Shapes',
    'photo.rectangle': 'Rectangle',
    'photo.circle': 'Circle',
    'photo.arrow': 'Arrow',
    'photo.colors': 'Colors',
    'photo.brush_size': 'Brush Size',
    'photo.text_size': 'Text Size',
    'photo.clear_all': 'Clear All',
    'photo.download': 'Download',
    'photo.caption': 'Photo Caption',
    'photo.caption_placeholder': 'Add a caption for this photo...',
    'photo.save': 'Save Photo',
  },
  fr: {
    // Navigation
    'nav.overview': 'Vue d\'Équipe',
    'nav.gantt': 'Gantt Annuel',
    'nav.projects': 'Projets',
    'nav.timetracking': 'Suivi du Temps',
    'nav.meetings': 'Réunions',
    'nav.analytics': 'Analyses',
    'nav.users': 'Utilisateurs',
    'nav.settings': 'Paramètres',
    
    // Header
    'header.title': 'Bureau d\'Études',
    'header.subtitle': 'Gestion de Projets & Gantt',
    
    // Auth
    'auth.signIn': 'Connectez-vous à votre compte',
    'auth.signin': 'Connectez-vous à votre compte',
    'auth.email': 'Adresse e-mail',
    'auth.emailPlaceholder': 'Entrez votre e-mail',
    'auth.password': 'Mot de passe',
    'auth.passwordPlaceholder': 'Entrez votre mot de passe',
    'auth.signingIn': 'Connexion...',
    
    // Projects
    'projects.title': 'Projets',
    'projects.subtitle': 'Gérer tous les projets du Bureau d\'Études',
    'projects.new_project': 'Nouveau Projet',
    'projects.search': 'Rechercher des projets...',
    'projects.no_projects': 'Aucun projet pour le moment.',
    'projects.no_search_results': 'Aucun projet trouvé correspondant à votre recherche.',
    
    // Project Form
    'project.edit': 'Modifier le Projet',
    'project.new': 'Nouveau Projet',
    'project.bc_order': 'Numéro de Commande Business Central',
    'project.lookup': 'Rechercher',
    'project.order_found': '✓ Commande trouvée et données importées',
    'project.name': 'Nom du Projet',
    'project.client': 'Client',
    'project.collection': 'Collection/Modèles',
    'project.composition': 'Composition',
    'project.date_brief': 'Date du Brief',
    'project.status': 'Statut',
    'project.commercial': 'Commercial/Chargé d\'affaires',
    'project.atelier': 'Atelier',
    'project.be_team': 'Membre Équipe BE',
    'project.key_dates': 'Dates Clés & Échéances',
    'project.start_be': 'Début en BE',
    'project.wood_foam': 'Lancement Bois/Mousse',
    'project.delivery': 'Livraison Prévue',
    'project.last_call': 'Dernier Appel',
    'project.hours_previewed': 'Heures Prévues',
    'project.hours_completed': 'Heures Réalisées',
    'project.view_gantt': 'Voir Gantt du Projet',
    'project.cancel': 'Annuler',
    'project.create': 'Créer le Projet',
    'project.update': 'Mettre à Jour le Projet',
    
    // Gantt
    'gantt.title': 'Vue d\'Ensemble Gantt Annuel',
    'gantt.subtitle': 'Projets triés par prochaine date clé',
    'gantt.project_column_title': 'Projet',
    'gantt.export': 'Exporter',
    'gantt.week': 'Semaine',
    'gantt.year': 'Année',
    'gantt.quarter': 'Trimestre',
    'gantt.month': 'Mois',
    'gantt.all_status': 'Tous les Statuts',
    'gantt.all_categories': 'Toutes les Catégories',
    'gantt.back_overview': 'Retour à la Vue d\'Ensemble',
    'gantt.key_dates': 'Dates Clés',
    'gantt.task_phase': 'Tâche / Phase',
    'gantt.no_tasks': 'Aucune tâche définie pour ce projet pour le moment.',
    'gantt.tasks_appear': 'Les tâches apparaîtront ici une fois créées.',
    'gantt.manage_tasks': 'Gérer les Tâches',
    'gantt.today': 'Aujourd\'hui',

    // Key Dates
    'gantt.wood_foam_launch': 'Lancement Bois/Mousse',
    'gantt.previewed_delivery': 'Livraison Prévue',
    'gantt.last_call': 'Dernier Appel',
    
    // Task Categories
    'overview.title': 'Vue d\'Ensemble de la Charge de Travail',
    'overview.subtitle': 'Analyse de la charge de travail et de la répartition des projets de l\'équipe BE',
    'overview.be_team_members': 'Membres de l\'Équipe BE',
    'overview.active_projects': 'Projets Actifs',
    'overview.overdue_projects': 'Projets en Retard',
    'overview.avg_utilization': 'Utilisation Moyenne',
    'overview.capacity': 'Capacité',
    'overview.overdue': 'en retard',
    'overview.total_hours': 'Heures Totales',
    'overview.completed': 'Terminé',
    'overview.no_active_projects': 'Aucun projet actif',
    'overview.available_assignment': 'Disponible pour de nouvelles affectations',
    'overview.progress': 'Progrès',
    'overview.next': 'Suivant',
    'overview.more_projects': 'projets supplémentaires',
    
    'task.be_plans_validation': 'BE plans pour validation',
    'task.be_etude_conception': 'BE étude conception',
    'task.commande_mousse': 'Commande mousse',
    'task.be_prepare_fichiers_decoupe': 'BE prépare fichiers découpe bois 2D / dossier atelier',
    'task.reception_mousse': 'Reception mousse',
    'task.decoupe_bois_montage': 'Découpe bois + montage',
    'task.reception_structure_bois': 'Reception structure bois à Chenn',
    'task.gandage_mise_mousse': 'Gandage et Mise en mousse',
    'task.reception_tissu': 'Reception tissu',
    'task.confection': 'Confection (coupe/couture)',
    'task.tapisserie': 'Tapisserie',
    'task.rdv_confort_test_atelier': 'Rdv confort test atelier',
    'task.rdv_confort_structure_bois': 'RDV confort sur structure bois canapé',
    'task.modifs_mousse_post_rdv': 'Modifs mousse post-rdv confort',
    'task.pose_sangles_toile': 'Pose des sangles et/ou toile polypro',
    'task.modifs_bois_post_montage': 'Modifs bois post-montage proto',
    'task.placage_bois': 'Placage bois',
    'task.vernis_placage_bois': 'Vernis placage bois',
    'task.rdv_confort_validation_blanc': 'Rdv confort / validation mise en blanc',
    'task.livraison_ebeniste': 'Livraison EBENISTE',
    'task.controle_qualite': 'Control Qualité',
    'task.depart_palette_moreau': 'Départ palette Moreau',
    'task.autre_a_definir': 'Autre à définir',
    
    // Task Management
    'tasks.manage': 'Gérer les Tâches du Projet',
    'tasks.reorder': 'Glisser pour réorganiser les tâches',
    'tasks.enabled_tasks': 'Tâches Activées',
    'tasks.available_tasks': 'Tâches Disponibles',
    'tasks.save': 'Enregistrer les Tâches',
    'tasks.cancel': 'Annuler',
    'tasks.edit_task': 'Modifier la Tâche',
    'tasks.task_name': 'Nom de la Tâche',
    'tasks.start_date': 'Date de Début',
    'tasks.end_date': 'Date de Fin',
    'tasks.assignee': 'Assigné à',
    'tasks.unassigned': 'Non Assigné',
    'tasks.status': 'Statut',
    'tasks.progress': 'Progrès',
    'tasks.dependencies': 'Dépendances',
    'tasks.dependencies_help': 'Sélectionnez les tâches qui doivent être terminées avant que cette tâche puisse commencer',
    'tasks.no_other_tasks': 'Aucune autre tâche disponible',
    
    // Sub Categories
    'subcategory.dev_in_progress': 'Projets en cours de développement',
    'subcategory.prod_with_be_tracking': 'Projets lancés en prod avec suivi BE',
    'subcategory.updates_nomenclature': 'Mises à jour à faire / Nomenclature édition à faire + surveiller vie série',
    'subcategory.waiting_order': 'Projets en attente de commande',
    'subcategory.completed': 'Projets Terminés',
    'subcategory.on_hold': 'Projets en Attente',
    
    // Status
    'status.planning': 'Planification',
    'status.in_progress': 'En Cours',
    'status.at_risk': 'À Risque',
    'status.overdue': 'En Retard',
    'status.completed': 'Terminé',
    'status.on_hold': 'En Attente',
    'status.pending': 'En Attente',
    'status.blocked': 'Bloqué',
    
    // Common
    'common.loading': 'Chargement...',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.close': 'Fermer',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.access_denied': 'Accès Refusé',
    'common.admin_required': 'Vous avez besoin de privilèges administrateur pour accéder à la gestion des utilisateurs.',
    
    // Users
    'users.title': 'Gestion d\'Équipe',
    'users.subtitle': 'Gérer les membres de l\'équipe, les rôles et les permissions',
    'users.users': 'utilisateurs',
    'users.add_user': 'Ajouter Utilisateur',
    'users.search': 'Rechercher des utilisateurs...',
    'users.all_roles': 'Tous les Rôles',
    'users.admin': 'Administrateur',
    'users.team_member': 'Membre d\'Équipe',
    'users.commercial': 'Commercial',
    'users.atelier': 'Atelier',
    'users.all_status': 'Tous les Statuts',
    'users.active': 'Actif',
    'users.inactive': 'Inactif',
    'users.pending': 'En Attente',
    'users.user': 'Utilisateur',
    'users.role': 'Rôle',
    'users.department': 'Département',
    'users.status': 'Statut',
    'users.last_login': 'Dernière Connexion',
    'users.actions': 'Actions',
    'users.never': 'Jamais',
    'users.permissions': 'Permissions',
    
    // Time Tracking
    'timetracking.title': 'Suivi du Temps',
    'timetracking.subtitle': 'Enregistrez vos heures quotidiennes et suivez l\'avancement des projets',
    'timetracking.add_entry': 'Ajouter une Entrée',
    'timetracking.today_hours': 'Heures d\'Aujourd\'hui',
    'timetracking.today_entries': 'Entrées d\'Aujourd\'hui',
    'timetracking.active_projects': 'Projets Actifs',
    'timetracking.project': 'Projet',
    'timetracking.select_project': 'Sélectionner un projet',
    'timetracking.hours': 'Heures',
    'timetracking.date': 'Date',
    'timetracking.task_category': 'Catégorie de Tâche',
    'timetracking.select_category': 'Sélectionner une catégorie',
    'timetracking.description': 'Description',
    'timetracking.description_placeholder': 'Décrivez le travail effectué...',
    'timetracking.save_entry': 'Enregistrer l\'Entrée',
    'timetracking.recent_entries': 'Entrées Récentes',
    'timetracking.no_entries': 'Aucune entrée de temps pour le moment',
    'timetracking.add_first_entry': 'Ajoutez votre première entrée pour commencer le suivi',
    'timetracking.enable_notifications': 'Activer les Rappels Quotidiens',
    'timetracking.notification_description': 'Recevez un rappel à 17h30 chaque jour pour enregistrer vos heures',
    
  // Meetings
  'meetings.title': 'Réunions',
  'meetings.subtitle': 'Gérer les réunions de projet et les notes',
    'meetings.new_meeting': 'Nouvelle Réunion',
    'meetings.edit_meeting': 'Modifier la Réunion',
    'meetings.search': 'Rechercher des réunions...',
    'meetings.all_projects': 'Tous les Projets',
    'meetings.no_meetings': 'Aucune réunion pour le moment',
    'meetings.create_first': 'Créez votre première réunion pour commencer',
    'meetings.project': 'Projet',
    'meetings.select_project': 'Sélectionner un projet',
    'meetings.date': 'Date',
  'meetings.title_field': 'Titre de la Réunion',
  'meetings.title_placeholder': 'Entrez le titre de la réunion...',
    'meetings.attendees': 'Participants',
    'meetings.people': 'personnes',
    'meetings.photos': 'Photos',
    'meetings.upload_photos': 'Télécharger des Photos',
    'meetings.photo_caption': 'Ajouter une légende...',
    'meetings.remove_photo': 'Supprimer la Photo',
    'meetings.notes': 'Notes de Réunion',
    'meetings.notes_placeholder': 'Entrez les notes de réunion...',
    'meetings.voice_notes': 'Notes Vocales',
    'meetings.start_voice': 'Démarrer Voix-vers-Texte',
    'meetings.stop_voice': 'Arrêter Voix-vers-Texte',
    'meetings.record_audio': 'Enregistrer Audio',
    'meetings.recording': 'Enregistrement',
    'meetings.voice_note': 'Note Vocale',
    'meetings.no_notes': 'Aucune note ajoutée',
    'meetings.created_by': 'Créé par',
    'meetings.view': 'Voir',
    'meetings.edit': 'Modifier',
    'meetings.delete': 'Supprimer',
    'meetings.create': 'Créer la Réunion',
    'meetings.update': 'Mettre à Jour la Réunion',
    'meetings.confirm_delete': 'Êtes-vous sûr de vouloir supprimer cette réunion ?',
    
    // Photo Editor
    'photo.edit_annotate': 'Modifier et Annoter la Photo',
    'photo.drawing_tools': 'Outils de Dessin',
    'photo.pen': 'Stylo',
    'photo.eraser': 'Gomme',
    'photo.text': 'Texte',
    'photo.shapes': 'Formes',
    'photo.rectangle': 'Rectangle',
    'photo.circle': 'Cercle',
    'photo.arrow': 'Flèche',
    'photo.colors': 'Couleurs',
    'photo.brush_size': 'Taille du Pinceau',
    'photo.text_size': 'Taille du Texte',
    'photo.clear_all': 'Tout Effacer',
    'photo.download': 'Télécharger',
    'photo.caption': 'Légende de la Photo',
    'photo.caption_placeholder': 'Ajouter une légende pour cette photo...',
    'photo.save': 'Enregistrer la Photo',
  }
};

export const useLanguageHook = () => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get saved language from localStorage or default to 'fr'
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'fr') ? saved : 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  return { language, setLanguage, t };
};
